import { Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fabrenix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${geistMono.variable} antialiased`}>
        <Navber></Navber>
        <div className=" h-[600px]">{children}</div>
      </body>
    </html>
  );
}
